<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://w3.org">

    <!-- Root Element Definition -->
    <xs:element name="university">
        <xs:complexType>
            <xs:sequence>
                
                <!-- Department Definition -->
                <xs:element name="department" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="budget" type="xs:decimal"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
                
                <!-- Course Definition -->
                <xs:element name="course" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="credits" type="xs:integer"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
